name: Main Branch workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'recette'
        run: |
          echo "ERROR: You can only merge to main from recette."
          exit 0

  build:
    needs: check_branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t djlopezz/cicdm1-front .
        docker push djlopezz/cicdm1-front

  # Hook:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: refresh webservice
  #     run: |
  #       curl -X POST "${{ secrets.RENDER_HOOK_URL }}"